config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landingpage#index'

  get '/users/test' => 'users#test', as: 'test'

  resources :landingpage
  resources :about_us
  resources :devise
  resources :items
  resources :users
  # resources :reviews

  get '/items/:id/review' => 'reviews#new', as: 'save_review'
  post '/items/:id/review' => 'reviews#create', as: 'create_review'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  validates :description,
  presence: true,
  length: {maximum: 50},
  on: :create,
  allow_nil: false
  # validates :description, length: { maximum: 200 }
end

app/models/landingpage.rb
class Landingpage < ApplicationRecord
end

app/models/review.rb
class Review < ActiveRecord::Base

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :item

end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(items)
    return items_path
  end

end

app/controllers/devises_controller.rb
class DevisesController < ApplicationController

def create
    # render plain: params[:item].inspect
    @item = Item.new(item_params)


    uploaded_file = params[:items][:image].path
    cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
    @item.image = cloudinary_file["secure_url"]
    puts "**********************"
    puts cloudinary_file["secure_url"]

    @item.save
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  def index
    # @items = Item.order(created_at: :desc).where(repairing: false, completed: false)
    @items = Item.order(created_at: :desc).where(repairing: false, completed: false).page(params[:page]).per_page(8)
  end

  def new
    @current = current_user.id
  end

  def create
    # render plain: params[:item].inspect
    @item = Item.new(item_params)

    # cloudinary feature for image upload
    uploaded_file = params[:items][:image].path

    cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
    @item.image = cloudinary_file["secure_url"]
    puts "**********************"
    puts cloudinary_file["secure_url"]

    @item.save
    redirect_to @item
    puts @item
  end

  def show
    @item = Item.find(params[:id])
    @current = current_user.id
    p "-=-================"
    p @item.id
  end

  def edit
    @item = Item.find(params[:id])
    @current = current_user.id
    p "======================="
    p @item
    p @current
    p "repairing", @item.repairing
    p "repairer", @item.repairer
  end

  def update
    #render plain: params.inspect
    @item = Item.find(params[:id])

    @item.update_attribute(:repairing, params[:item][:repairing])
    @item.update_attribute(:repairer, params[:item][:repairer])
    @item.update_attribute(:description, params[:item][:description])

    @item.update_attribute(:completed, params[:item][:completed])
    # render plain: params.inspect
    redirect_to "/items/"+params[:id]+"/"
  end

  def destroy

  end

  private
  #Qns for Ben from WenLei wld this 2 item_params conflict? 21/08/2019 9:27PM
  #WenLei item_params
  # def item_params
  #   params.require(:items).permit(:name, :description, :image, :user_id)
  # end

  #Ben item_params
  def item_params
    params.require(:items).permit(:name, :description, :image, :user_id, :repairing, :completed, :repairer, :reviewed)
  end
end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
    def index
        # @items = Item.all
    puts "****************"
    puts "USEEEEER"
    #puts current_user.id
    @items = Item.where(repairing: false, completed: false)
        if @items.length > 10
            @finalItems = @items[-10,10]
        else
            @finalItems = @items
        end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
  def new
    @item = Item.find(params[:id])
  end
  def create
    @reviews = Review.new(review_params)
    @item = Item.find(params[:id])
    @item.reviewed = true

    p "=============================="
    p @reviews
    @reviews.save
    @item.save
    redirect_to "/users/"+@reviews.user_id_id.to_s+"/"
  end
  def show
  end
  def edit
  end
  def update
  end
  def destroy
  end
  private
    def review_params
      params.require(:reviews).permit(:review, :rating, :item_id, :repairer_id, :user_id_id)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [ :show, :index ]

  def index
    @items = Item.where(repairing: false)
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @brokenitems = Item.where(user_id: params[:id], repairing: false, completed: false)
    @underrepair = Item.where(user_id: params[:id], repairing: true, completed: false)
    @repaireditems = Item.where(user_id: params[:id], repairing: false, completed: true)
    @fixingitems = Item.where(repairer: params[:id], repairing: true, completed: false)
    @itemsfixed = Item.where(repairer: params[:id], repairing: false, completed: true)
    @reviews = Review.where(repairer_id: params[:id].to_i)


    # @allitems = Item.where(user_id: params[:id])
    # @repaireditems = Item.where(repairer: params[:id])
    # p "my repaired items"
    # p @repaireditems
    # p @repaireditems[0].user_id
    # @items = Item.where(user_id: params[:id].to_i, repairing: false, completed: false)
    # puts "===================================="
    # p @items.name
    # p @items
    # @repairingitems = Item.where(user_id: params[:id].to_i,repairing: true, completed: false)
    # @completeditems = Item.where(user_id: params[:id].to_i,repairing: false, completed: true)

    # @repairingothers = Item.where(repairer: current_user.id, repairing: true, completed: false)
    # @completedothers = Item.where(repairer: current_user.id, repairing: false, completed: true)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

  end

  def destroy

  end

  def test

  end

end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    unless options[:renderer]
      options = options.merge :renderer => BootstrapRenderer
    end
    super *[collection_or_options, options].compact
  end
  class BootstrapRenderer < WillPaginate::ActionView::LinkRenderer
    protected
    def html_container(html)
      tag :nav, tag(:ul, html, class: "pagination pagination-sm"), container_attributes
    end
    def page_number(page)
      tag :li, link(page, page, rel: rel_value(page), class: 'page-link'),
        class: (page == current_page ? 'page-item active': 'page-item')
    end
    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#', class: 'page-link'),
        class: ['page-item', classname, ('disabled' unless page)].join(' ')
    end
  end
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/views/about_us/index.html.erb
<div class= "container" style="margin: 10px auto;">
<div class= "row">
    <h2>About Us</h2>
    </div>
    <div class="row">
      <div class="col-lg-6">
      <p></p>
        <div>Where and When?</div>
        <br>
        <ul>
          <li>
          Fix and Break is avaliable to access anytime, anywhere 24/7, 365 days a year. Just post your item and a repairman will be on his way.
          </li>
          <li>
            If you would like to be a repairman, simply sign up and see projects avaliable for tinkering.
          </li>
          <li>
          Stay tuned to our FB Fix and Break for the latest updates, special events and save the date!
          </li>
        </ul>
        <div>What items to bring?</div>
        <br>
        <ul>
          <li>Bring your broken electrical appliances, clothes that need mending, or broken household items that could use a new lease of life.</li>
        </ul>
        <div>How to fix it?</div>
        <br>
        <ul>
          <li>Our Repair Coaches will assess the condition of your item. If it’s within their repair capability, they will direct you to the appropriate station after making sure you have read and signed off on the Repair Kopitiam house rules.
          </li>
          <li>
          You will be guided by our Repair Coaches to first diagnose the fault with the item, explore methods of rectification and then start repairing it.
          </li>
          <li>
          While our Repair Coaches have undergone some training before each session, it is quite possible that the repair job may not work out due unavailability of certain tools or spare parts.</li>
        </ul>
      </div>
      <div class="col-lg-6" style="margin: auto;">
        <img class="img-fluid rounded" src=<%= image_url ('landingpage/image1.jpg')%> />
      </div>
    </div>
    </div>

app/views/items/edit.html.erb
<% if @current == @item.repairer.to_i && @item.repairing == true %>
	<p>you are repairing this<p>
	<%= form_with scope: :items, model: @item, local: true do |form| %>
				<input type="hidden" name="item[repairing]" value="false">
				<input type="hidden" name="item[completed]" value ="true">
				<input type="hidden" name="item[repairer]" value="<%=@current%>">
				<input type="hidden" name="item[description]" value="<%=@item.description%>">
				<button type="submit">Completed</button>
	<% end %>
	<%= form_with scope: :items, model: @item, local: true do |form| %>

<div class="container">
	<div class="row">
		<div class="card  m-auto" style="width: 21rem;">
			<div class="card-body">
				<img src="<%= image_url (@item.image) %>" class="card-img-top img-fluid">

				<br>
			<br>
          <h5>
			    <%= form.label :description %><br>
			    <textarea rows="4" cols="26" name="item[description]"><%= @item.description %></textarea>
			  </h5>
			  <div class="col text-center"><button class="btn btn-outline-success" type="submit">Update</button></div>
			  </div>
		</div>
	</div>
</div>
			  <input type="hidden" name="item[repairing]" value="true">
			  <input type="hidden" name="item[repairer]" value="<%=@current%>">
			  <input type="hidden" name="item[completed]" value="false">

	<% end %>
<% elsif @current == @item.user_id && @item.repairing == false %>
	<%= form_with scope: :items, model: @item, local: true do |form| %>
				<input type="hidden" name="item[repairing]" value="false">
				<input type="hidden" name="item[completed]" value ="false">
				<input type="hidden" name="item[repairer]" value="null">

<div class="container">
	<div class="row">
		<div class="card  m-auto" style="width: 21rem;">
			<div class="card-body">
				<img src="<%= image_url (@item.image) %>" class="card-img-top img-fluid">
			<br>
			<br>
				<h5 class="card-title">
					<%= form.label :description %>
				</h5>
					<textarea rows="4" cols="26" name="item[description]"><%= @item.description %></textarea>
					<div class="col text-center"><button class="btn btn-outline-success" type="submit">Update</button></div>
			</div>
		</div>
	</div>
</div>

	<% end %>

<% elsif @current == @item.repairer.to_i && @item.completed == true %>
	<p>You have repaired this<p>
<% elsif @current == @item.user_id && @item.repairing == true %>
	<p>your item is under repair by others</p>
<% elsif @current == @item.user_id && @item.completed == true %>
	<p>your item is repaired by others</p>

<% end %>

app/views/items/index.html.erb
<%= stylesheet_link_tag "items_index" %>

  <!-- Page Content -->
  <div class="container">

    <!-- Latest Listing Section -->
    <h2>Latest Items Posted</h2>

    <div class="row">

		 <% @items.each do |item| %>
    	 <div class="col-lg-3 col-sm-6 portfolio-item">
      	 <div class="card h-100">
	      	 <div class="item-list-card"><a href="/items/<%= item.id%>"><img class="card-img-top" src="<%= image_url (item.image)%>" /></a></div>
        	 <div class="card-body">
        	 	<h5 class="card-title">
        	 		<a href="/items/<%= item.id%>"><%= item.name.titlecase %></a>
        	 	</h5>
        	 		<p class="card-text-posted-by">Owner: <a href="/users/<%= item.user_id%>"><%= item.user.username %></a></p>
	      	 		<p class="card-text-timestamp"><%= time_ago_in_words(item.created_at) %> ago </p>
	      	 		<p class="card-text text-truncate"><%= item.description %></p>
    	 		</div>
  	 		</div>
	 		</div>
		 <% end %>
    </div>
    <%= will_paginate @items, params: @will_paginate_params, class: 'text-center' %>
    <!-- /.row End of Latest Listing -->

    <hr>

    <!-- Call to Action Section -->
    <div class="row mb-4">
      <div class="col-md-8">
        <p>Do you have a household item that needed repair? <br /> Add your items to our community of tinkerers to help you fix it. </p>
      </div>
      <div class="col-md-4">
        <a class="btn btn-primary btn-lg btn-block" href="/items/new">Add Item</a>
      </div>
    </div>

  </div>
  <!-- /.container -->

app/views/items/new.html.erb
<div class="row">
	<div class="col-md-4" style="margin: 20px auto;">
		<h2>Add New Item</h2>

		<!-- Start of Form -->
		<%= form_with scope: :items, url: items_path, local: true do |form| %>

		  <!-- name -->
		  <div class="form-group">
		    <%= form.label :name %><br>
		    <%= form.text_field :name, class: "form-control" %>
		  </div>

		  <!-- description -->
		  <div class="form-group">
		    <%= form.label :description %><br>
		    <%= form.text_area :description, id: "counted", maxlength: 50, size: 50, class: "form-control" %>
		    <p>Current character count: <span id="char-count">0</span> / 50 </p>

		  </div>

		  <!-- image -->
		  <div class="form-group">
		    <%= form.label :image %><br>
		    <%= form.file_field :image, class: "form-control" %>

		  </div>

		  <input type="hidden" name="items[user_id]" value="<%= @current%>">
		  <input type="hidden" name="items[repairing]" value="false">
		  <input type="hidden" name="items[completed]" value="false">
		  <input type="hidden" name="items[repairer]" value="null">
		  <input type="hidden" name="items[reviewed]" value="false">

		  <p>
		    <%= form.submit class: "btn btn-primary" %>
		  </p>
		<% end %>
	</div>
</div>


<script type="text/javascript">
	$(document).ready(function() {
	  $('#char-count').html($('#counted').val().replace(/\n/g, "\n\r").length);
	});

	$('#counted').keyup(function() {
	  $('#char-count').html($(this).val().replace(/\n/g, "\n\r").length);
	});
</script>

app/views/items/show.html.erb
<div class="container content-middle-vertical">
<div class="row">
            <h2><%= @item.name.titlecase %></h2>
</div>
<div class="card card-body">
<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-body">
				<input type="hidden" class="item-images-json" value="[]">
				<div class="card-block">
                <a class="img-link" href="/users/<%= @item.user_id%>">
					<%= image_tag(@item.image, :class => "fit-image img-brad") %>
				</a>
				</div>
				<hr>
				<h3>Product Description</h3>
				<%= @item.description %>
			</div>
		</div>
	</div>

	<div class="col-md-4" style="border-left: 1px solid lightgrey;">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>Product Details</h4>
			</div>
            <hr>
			<div class="panel-body">

				<div class="clearfix">
					<p class="card-text-posted-by"><strong>Posted By: </strong><a href="/users/<%= @item.user.id%>"><%= @item.user.username %></a><br>
                    <strong>Date Posted</strong>: <%= @item.created_at %></<strong></p>
					<div class="col-md-6">
						<%#<a href="#_" class="monospaced"><span class="glyphicon glyphicon-pencil"></span> Write a Review</a> %>
					</div>
				</div>

				<hr>
                    <% if @current == @item.user_id && @item.repairing == false && @item.completed == false%>
	<p>item still waiting for help</p>
	<a href="/items/<%= @item.id%>/edit">
		<button class="btn btn-primary btn-block" class="glyphicon glyphicon-star">Click here to edit</button>
	</a>

    <% elsif @current == @item.user_id && @item.repairing == true && @item.completed == false%>
	<a href="/items/<%= @item.id %>/edit">
		<button class="btn btn-primary btn-block" class="glyphicon glyphicon-star">Items under repair</button>
	</a>
    <% elsif @current == @item.user_id && @item.completed == true && @item.repairing == false %>
	<% if @item.reviewed == false %>
		<a href="/items/<%= @item.id%>/review">
			<button class="btn btn-primary btn-block" class="glyphicon glyphicon-star">Leave a review</button>
		</a>
	<% else %>
		<p>You have left a review<p>
	<% end %>
    <% elsif @current == @item.repairer.to_i && @item.repairing == true && @item.completed == false %>

	<a href="/items/<%= @item.id %>/edit">
		<button class="btn btn-primary btn-block" class="glyphicon glyphicon-star">You are repairing</button>
	</a>
    <% elsif @current == @item.repairer.to_i && @item.completed == true && @item.repairing == false %>
	<% if @item.reviewed == true %>
		<p>You have completed the item and owner has reviewed your work</p>
	<% else %>
		<p>You have completed the item</p>
	<% end %>
    <% elsif @current ==! @item.repairer.to_i && @item.repairing == true && @item.completed == false %>
	<p>item under repair by others</p>
    <% elsif @current ==! @item.repairer.to_i && @item.completed == true && @item.repairing == false %>
	<p>item completed by others</p>
    <% else %>
	<%= form_with scope: :items, model: @item, local: true do |form| %>
				<input type="hidden" name="item[repairing]" value="true">
				<input type="hidden" name="item[repairer]" value="<%=@current%>">
				<input type="hidden" name="item[description]" value="<%=@item.description%>">
				<input type="hidden" name="item[completed]" value="false">
				<button class="btn btn-primary btn-block" type="submit" >I WANT TO REPAIR</button>
	<% end %>
    <% end %>
			</div>
		</div>
        <%# <hr>
		<div class="panel panel-default">
			<div class="panel-heading">
			</div>
			<div class="panel-body">
			</div>
		</div>
        %>
	</div>
</div>
</div>
</div>

app/views/landingpage/index.html.erb
<%= stylesheet_link_tag "landingpage" %>
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner text-shadow-border" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image:url(<%= image_url('landingpage/slide1.jpg') %>)">
          <div class="carousel-caption d-none d-md-block">
            <h1>Love Your Things?</h1>
            <p>Fix Your Things.</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url(<%= image_url('landingpage/slide2.jpg') %>)">
          <div class="carousel-caption d-none d-md-block">
            <h1>Repair Your Junk</h1>
            <p>An Initiative Brought To You By SEI19 Proj3 Group 2.</p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url(<%= image_url('landingpage/slide3.jpg') %>)">
          <div class="carousel-caption d-none d-md-block">
            <h1>Save the Environment</h1>
            <p>and save money too!</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

    <h2 class="my-4">What to Fix?</h2>

    <!-- Marketing Icons Section -->
    <div class="row">
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Electricals</h4>
          <div class="card-body">
            <p class="card-text text-wrap">Is your toaster always tripping? Or is your kettle wire exposed? Or is your standing fan busted? At this station you can learn how to identify electrical faults, splice wires and re-solder broken connections.</p>
          </div>
          <div class="card-footer">
            <a href="/items" class="btn btn-primary">See Electricals</a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Fabric</h4>
          <div class="card-body">
            <p class="card-text text-wrap">Have holes in your socks? Or have the buttons from your favourite shirt come loose? Perhaps the hem of your skirt has started to fray? Bring in articles of clothing or even fabric material to mend or re-purpose into something useful!</p>
          </div>
          <div class="card-footer">
            <a href="/items" class="btn btn-primary">See Fabric</a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">Mechanical</h4>
          <div class="card-body">
            <p class="card-text text-wrap">Do you have a stool that is wonky? Or perhaps a broken ceramic fridge magnet? Everyone has odds and ends around the house that could use a glue job or some simple fixes to make it more stable.</p>
          </div>
          <div class="card-footer">
            <a href="/items" class="btn btn-primary">See Mech</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->

    <!-- Portfolio Section -->
    <h2>Some Items to tinker with</h2>

<div class="scrollmenu">
    <div class="row flex-row flex-nowrap">
      <% @finalItems.each do |item| %>
          <div class="col-lg-3 col-sm-6 col-xs-6 portfolio-item">
      	 <div class="card h-100">
	      	 <div class="item-list-card"><a href="/items"><img class="card-img-top" src=<%= image_url (item.image)%> /></a></div>
        	 <div class="card-body">
        	 	<h4 class="card-title">
        	 		<a href="/items"><%= item.name.titlecase %></a>
      	 		</h4>
      	 		<p class="card-text text-wrap"><%= item.description %></p>
    	 		</div>
  	 		</div>
	 		</div>
		 <% end %>
    </div>
    </div>
    <!-- /.row -->

    <!-- Features Section -->
    <div class="row">
        <h2>What others say about us</h2>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
                    <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
                    <p class="mb-0 mt-2 font-italic">“It’s such a great learning experience for me and my kids. Instead of playing computer games on their days off from school and tuition, it would be better if they continue coming for this paper editor online! They love it and have started telling all their friends about it!”</p>
                    <footer class="blockquote-footer pt-4 mt-4 border-top">Cindy (Visitor)
                    </footer>
                </blockquote>
      </div>
      <div class="col-lg-4">
        <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
                    <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
                    <p class="mb-0 mt-2 font-italic">“This exchange of knowledge is certainly one of the reasons why I keep coming down.”</p>
                    <footer class="blockquote-footer pt-4 mt-4 border-top">Coach Agatha
                    </footer>
                </blockquote>
      </div>
      <div class="col-lg-4">
        <blockquote class="blockquote blockquote-custom bg-white p-5 shadow rounded">
                    <div class="blockquote-custom-icon bg-info shadow-sm"><i class="fa fa-quote-left text-white"></i></div>
                    <p class="mb-0 mt-2 font-italic">“How much work that goes into making something, the sweat and time, goes unappreciated. The exposure to repair in Repair Kopitiam helps people, especially children, understand the value of objects.”</p>
                    <footer class="blockquote-footer pt-4 mt-4 border-top">Dr Kiruthika (Visitor)
                    </footer>
                </blockquote>
      </div>
    </div>

    <hr>
    <!-- /.row -->

    <!-- Call to Action Section -->
    <div class="row mb-4">
      <div class="col-md-8">
        <h4>Come contribute with us today!</h4>
      </div>
      <div class="col-md-4">
        <a class="btn btn-lg btn-secondary btn-block" href="/users/sign_up" style="font-size: 1.2rem;">Get Started</a>
      </div>
    </div>

  </div>
  <!-- /.container -->

app/views/reviews/new.html.erb
<h1>ADD REVIEW FOR <%= @item.name.upcase %></h1>
<%= form_with scope: :reviews, url: create_review_path, local: true do |form| %>
	<div class="form-group">
		    <%= form.label :review %><br>
		    <%= form.text_field :review, class: "form-control" %>
	</div>

	<div class="form-group">
		    <%= form.label :rating %><br>
		    <%= form.text_area :rating, class: "form-control" %>
	</div>
	<input type="hidden" name="reviews[item_id]" value="<%= @item.id%>">
	<input type="hidden" name="reviews[repairer_id]" value="<%= @item.repairer.to_i%>">
	<input type="hidden" name="reviews[user_id_id]" value="<%= @item.user_id%>">

	<p>
		<%= form.submit class: "btn btn-primary" %>
	</p>
<% end %>